[build]
  command = "npm run build:ssr"
  publish = "dist/crudApp/browser"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200