[build]
  command = "npm run build:ssr"
  publish = "dist/crudApp/browser"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true